# This is a basic workflow that is manually triggered

name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    # Runs a single command using the runners shell
    - run: sudo npm install -g yarn
    - run: yarn install
    - run: yarn prettier:check
    - run: yarn test
