name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - name: install
      - run: sudo npm install -g yarn
      - run: yarn install
      - name: test
      - run: yarn prettier:check
      - run: yarn test
